spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: api-1
            uri: lb://NIS
            predicates:
            - Path=/save/product
  application:
    name: Gateway
server:
  port: 3333
eureka:
  client:
    service-url: 
      defaultzone: http://localhost:8761/eureka



      
