spring:
  application:
    name: NIS
  datasource:
    url: jdbc:oracle:thin:@DESKTOP-14G8JJ6:1521/XEPDB1
    username: system
    password: Hrithik_2025
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      productFallback:
        registerHealthIndicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
